# Generated by Django 5.1.5 on 2025-04-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_book_category_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
