# Generated by Django 5.1.5 on 2025-04-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_remove_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='book.category'),
        ),
    ]
