# Generated by Django 5.1.5 on 2025-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_tradeoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
    ]
