# Generated by Django 5.1.5 on 2025-04-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_tradeoffer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
